### ISSUE TITLE
Invalid documentation keyword

### ISSUE THREAD

**Issue by piv199** [rambler-ios/RamblerAppDelegateProxy#10]
<img width="767" alt="screen shot 2017-02-19 at 11 19 25" src="https://cloud.githubusercontent.com/assets/8293191/23101107/d5403590-f695-11e6-88b2-a8692e7c0608.png">

Xcode 8.2.1 makes warning for @return keyword in documentation inside RamblerAppDelegateProxyInjector.h. Would you be mind to fix this warning?

**Comment by CognitiveDisson** [comment]
@piv199 Thanks for your investigation. This bug is fixed in version 0.0.5.
