### ISSUE TITLE
swift gist usage problem

### ISSUE THREAD

**Issue by Maxatma** [rambler-ios/RamblerAppDelegateProxy#12]
Hi, I'm trying to use your awesome gist: https://gist.github.com/CognitiveDisson/8bea14e2578a213478f0d6d3f8d30c07
for swift projects.
Problem is that we can't invoke 2 same methods for multiple handlers (which is possible in your objc-example), so it loses any sense. 

There is the minimal code:
https://github.com/Maxatma/AppDelegateProxySwiftExample
Let me know if I'm doing it right:

For example, this part:
```
@UIApplicationMain
public class AppDelegateProxy: NSObject, UIApplicationDelegate {
	public var handlers: [AppDelegateHandler] = [
		RemoteNotificationHandler(),
		SomeOtherHandler(),
	]
```

Any idea to fix it?
Thanks!

**Comment by akkrat** [comment]
hi
Nope. Objective-C implementation uses NSInvocation, which is unavailable in Swift. So you can use this proxy only for methods grouping (i.e. handlers work like an usual UIApplicationDelegate extensions)

**Comment by Maxatma** [comment]
Hm, thanks anyway
