### ISSUE TITLE
уточнение поведения RamblerAppDelegateProxy

### ISSUE THREAD

**Issue by waphumanoid** [rambler-ios/RamblerAppDelegateProxy#8]
Добрый день.
Хотел бы уточнить поведение. 
Я делаю вызов `[[RamblerAppDelegateProxy injector] setDefaultAppDelegate:[AppDelegate new]];` в main, затем добавляю делегаты через `[RamblerAppDelegateProxy injector] addAppDelegates:@[[Delegate1 new], [Delegate2 new]]...`

После этого при вызове системой, например, метода `- (void)applicationDidBecomeActive:(UIApplication *)application`, который прописан явно во всех трех делегатах (AppDelegate, Delegate1, Delegate2), вызывается он только в Delegate1 и Delegate2, кроме AppDelegate (но я ожидаю).

Почему так? И запрещено здесь, как я понял:

```
- (void)forwardInvocation:(NSInvocation *)invocation {
    SEL selector = [invocation selector];

    if ([self shouldForwardToSelf:selector]) {
        [invocation invokeWithTarget:self];
    }

    BOOL hasResponder = NO;

    if ([self shouldForwardToDelegatesSelector:selector]) {
        for (id target in self.delegates) {
            if ([target respondsToSelector:selector]) {
                [invocation invokeWithTarget:target];
                hasResponder = YES;
            }
        }
    }

    if (hasResponder) return; <<<-----------------------------
    [invocation invokeWithTarget:self.defaultAppDelegate];
}
```

Спасибо.

**Comment by CognitiveDisson** [comment]
Добрый. Спасибо за интересный вопрос. Вы поняли все правильно. Такое поведение заложено специально. Так как предполагается, что DefaultAppDelegate будет использоваться исключительно для обработки системных вызовов UIKit - обработка событий пришедших по Responder Chain и т.д. И при возможности не содержит логику.
Обработка методов протокола UIApplicationDelegate должна быть в инстансах объектов из массива appDelegates.
Обычно в наших приложениях метод applicationDidBecomeActive есть в классе ответственном за обработку состояния приложения. Например если приложение пробыло в свернутом состоянии больше определенного времени, то показывает UI для ввода пароля - часто такое делают на нотификациях о изменение состояния.
В данный момент не вижу обстоятельств при которых такая обработка должна быть именно в DefaultAppDelegate. Если ситуация именно такая, уточните пожалуйста, что вы хотите делать в этом методе.
Если подытожить, причина идеологическая.

**Comment by waphumanoid** [comment]
Спасибо за разъяснение :). Сперва подумал, что я пропустил какую-то техническую особенность...
