### ISSUE TITLE
Swift usage?

### ISSUE THREAD

**Issue by Xpressive** [rambler-ios/RamblerAppDelegateProxy#9]
Добрый день. 
Хотел начать использовать это в своем проекте на Swift, но столкнулся с парой проблем. Вот мой main.swift файл:

```
RamblerAppDelegateProxy.injector().addAppDelegates([RemoteNotificationAppDelegate()])
RamblerAppDelegateProxy.injector().defaultAppDelegate = AppDelegate()

UIApplicationMain(Process.argc,
                  Process.unsafeArgv,
                  nil,
                  NSStringFromClass(RamblerAppDelegateProxy))

```

За defaultAppDelegate взял свой старый AppDelegate. Однако такой подход не работает :( В одном из классов пытался получить инстанс своего AppDelegate:

`let appDel = RamblerAppDelegateProxy.injector().defaultAppDelegate as! AppDelegate`

На что упорно получаю nil. Но если же я устанавливаю defaultAppDelegate не в main файле, а прямо перед тем как его вызвать, то он работает как положено(за исключением того, что инициализировать AppDelegate не при запуске, а "как-нибудь потом" вообще не вариант). 

А еще было бы круто, если бы появился пример этого всего на свифте :) 
С удовольствием подготовил бы его сам(но, для этого, хотелось бы, что-бы это как минимум у меня работало)

**Comment by CognitiveDisson** [comment]
Добрый. Спасибо за вопрос.
К сожалению, pod не поддерживает работу с Swift из за отсутствия рантайма. Для реализации такого подхода мы советуем использовать [gist](https://gist.github.com/CognitiveDisson/8bea14e2578a213478f0d6d3f8d30c07).
Но даже, если бы вы использовали Objective C, то запрашивать defaultAppDelegate таким способом некорректно. Правильный вариант:

```
id<RamblerAppDelegateProxyProtocol> appDelegateProxy = (id<RamblerAppDelegateProxyProtocol>)[[UIApplication sharedApplication] delegate];
id defaultAppDelegate = [appDelegateProxy defaultAppDelegate];
```
